server:
  port: 8080
  shutdown: graceful
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

spring:
  application:
    name: monolith-starter
  profiles:
    active: local
  output:
    ansi:
      enabled: always
  sql:
    init:
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/local_monolith_starter?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
  mail:
    host: localhost
    username: hello
    password: hello
    port: 1025

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ["health", "info"]
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  info:
    git:
      mode: simple
  health:
    mail.enabled: false

application:
  version: #project.version#
  secret: VUjx6MNon86YtxPxAAoJtIKbwSIkBGan0KriPgsb3E61c4zd
  jwt-validity-seconds: 86400
  confirmation-token-validity-minutes: 60
